# Generated by Django 4.2.30 on 2026-06-07 15:48

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_suspended', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ForumDiskusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=30, unique=True)),
                ('jabatan', models.CharField(default='Guru Mata Pelajaran', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guru_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JadwalKBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=10)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_list', to='lms.guru')),
            ],
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(choices=[('X', 'Kelas X'), ('XI', 'Kelas XI'), ('XII', 'Kelas XII')], max_length=3)),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_list', to='lms.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='Pertemuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('urutan', models.IntegerField(default=1)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertemuan_list', to='lms.jadwalkbm')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('guru', 'Guru'), ('siswa', 'Siswa')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.CharField(max_length=30, unique=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa_list', to='lms.kelas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siswa_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TugasUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('tugas', 'Penugasan'), ('kuis', 'Kuis / CBT')], max_length=10)),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('waktu_pengerjaan', models.IntegerField(default=60, help_text='Duration in minutes for quiz/CBT')),
                ('pertemuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_ujian_list', to='lms.pertemuan')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('pilihan_ganda', 'Pilihan Ganda'), ('esai', 'Esai')], default='pilihan_ganda', max_length=20)),
                ('pertanyaan', models.TextField()),
                ('opsi_a', models.CharField(blank=True, max_length=255, null=True)),
                ('opsi_b', models.CharField(blank=True, max_length=255, null=True)),
                ('opsi_c', models.CharField(blank=True, max_length=255, null=True)),
                ('opsi_d', models.CharField(blank=True, max_length=255, null=True)),
                ('opsi_e', models.CharField(blank=True, max_length=255, null=True)),
                ('jawaban_benar', models.CharField(blank=True, help_text='A/B/C/D/E for multiple choice, or text for esai key', max_length=5, null=True)),
                ('kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal_list', to='lms.tugasujian')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('nilai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lms.tugasujian')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lms.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_siswa', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lms.quizattempt')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.quizsoal')),
            ],
        ),
        migrations.CreateModel(
            name='PreRegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_nisn', models.CharField(max_length=30, unique=True)),
                ('role', models.CharField(choices=[('guru', 'Guru'), ('siswa', 'Siswa')], max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='PortofolioSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('proyek', 'Karya Proyek'), ('source_code', 'Source Code / Git Repositori'), ('sertifikat', 'Sertifikat Kompetensi'), ('praktik', 'Dokumentasi Praktik Kejuruan')], max_length=20)),
                ('deskripsi', models.TextField()),
                ('file_dokumentasi', models.FileField(blank=True, null=True, upload_to='portofolio_files/')),
                ('link_tautan', models.URLField(blank=True, help_text='Link to project live version, GitHub, or YouTube video', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portofolio_list', to='lms.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringPKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_industri', models.CharField(max_length=150)),
                ('alamat_industri', models.TextField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('guru_pembimbing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pkl_bimbingan', to='lms.guru')),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pkl_profile', to='lms.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='MateriMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('modul', 'Modul Digital (PDF/Word/PPT)'), ('audiovisual', 'Media Audiovisual (Video Link/Embed)'), ('link', 'Link Eksternal (Artikel/Repositori)')], max_length=20)),
                ('judul', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='materi_files/')),
                ('video_embed', models.TextField(blank=True, help_text='Embed code or direct YouTube URL', null=True)),
                ('link_eksternal', models.URLField(blank=True, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('pertemuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi_list', to='lms.pertemuan')),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('kategori', models.CharField(choices=[('nasional', 'Muatan Nasional'), ('kewilayahan', 'Muatan Kewilayahan'), ('kejuruan', 'Muatan Kejuruan')], max_length=20)),
                ('jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapel_list', to='lms.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('gmeet', 'Google Meet'), ('zoom', 'Zoom')], max_length=10)),
                ('link', models.URLField()),
                ('waktu_mulai', models.DateTimeField()),
                ('pertemuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class', to='lms.pertemuan')),
            ],
        ),
        migrations.CreateModel(
            name='KomentarForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konten', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar_list', to='lms.forumdiskusi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_komentar_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jadwalkbm',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_list', to='lms.kelas'),
        ),
        migrations.AddField(
            model_name='jadwalkbm',
            name='mata_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_list', to='lms.matapelajaran'),
        ),
        migrations.AddField(
            model_name='forumdiskusi',
            name='pertemuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_list', to='lms.pertemuan'),
        ),
        migrations.CreateModel(
            name='AktivitasPresensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batas_waktu', models.DateTimeField()),
                ('pertemuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi_activity', to='lms.pertemuan')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='TugasSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='submission_files/')),
                ('link', models.URLField(blank=True, help_text='Link GitHub or Google Drive', null=True)),
                ('jawaban_teks', models.TextField(blank=True, null=True)),
                ('nilai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.siswa')),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.tugasujian')),
            ],
            options={
                'unique_together': {('tugas', 'siswa')},
            },
        ),
        migrations.CreateModel(
            name='PresensiSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alpa', 'Alpa')], max_length=10)),
                ('waktu_absen', models.DateTimeField(default=django.utils.timezone.now)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('presensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi_list', to='lms.aktivitaspresensi')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi_list', to='lms.siswa')),
            ],
            options={
                'unique_together': {('presensi', 'siswa')},
            },
        ),
        migrations.CreateModel(
            name='JurnalPKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minggu_ke', models.IntegerField()),
                ('tanggal_awal', models.DateField()),
                ('tanggal_akhir', models.DateField()),
                ('kegiatan', models.TextField(help_text='Deskripsi kegiatan praktik mingguan')),
                ('status_absensi', models.CharField(choices=[('hadir', 'Hadir'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alpa', 'Alpa')], default='hadir', max_length=10)),
                ('file_laporan', models.FileField(blank=True, help_text='Dokumentasi foto kegiatan / file PDF laporan mingguan', null=True, upload_to='pkl_files/')),
                ('nilai_industri', models.DecimalField(blank=True, decimal_places=2, help_text='Nilai dari pembimbing industri', max_digits=5, null=True)),
                ('catatan_pembimbing', models.TextField(blank=True, help_text='Catatan umpan balik guru pembimbing', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('pkl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurnal_list', to='lms.monitoringpkl')),
            ],
            options={
                'unique_together': {('pkl', 'minggu_ke')},
            },
        ),
    ]
